// Code generated by govalid. DO NOT EDIT.

package config

import "fmt"

func (d Dict) Validate() error {
	switch d {
	case Dynamic:
		return nil
	case DynamicKeys:
		return nil
	case Static:
		return nil
	}
	return fmt.Errorf("invalid value")
}
